import React, { Component } from 'react';

class EventAgreement extends Component {
    render() {
        return (
            <div className="container">
            <h5>Rental Terms and Conditions</h5>
                <p>
                1st Stop Event Space <br/>
                444 Hightland Ave NE, Atlanta Ga 30312 <br/>

RENTAL TERMS, CONDITIONS, AND RENTAL ORDER IMPORTANT – READ AND SIGN THE FOLLOWING RENTAL TERMS, CONDITIONS, AND THE RENTAL ORDER FORM 1ST STOP EVENT SPACE'S RENTAL AGREEMENT & AND ARE BINDING UPON CUSTOMER ORDER: <br/>

I. Rental Terms and Conditions <br/>

1. Customer shall use all property in a careful and proper manner, shall comply with all applicable laws and regulations, and shall return the property in the same condition and good repair as when received. Customer hereby assumes all risk of loss and damage to the property from any cause whatsoever. <br/>

2. Customer acknowledges that the rental property is of a size, design, and capacity selected by customer, and that 1st Stop Event Space, LLC disclaims all warranties express or implied with respect to the rental property, including any express or implied warranties as to condition, fitness for a particular purpose or durability. Under no circumstances will 1st Stop Event Space, LLC be liable for any incidental, special, punitive or consequential damages arising out of or in connection with the rental property. <br/>

3. Responsibility of the rentals remains with the customer from the time of delivery until the time of return. Customer agrees that all rentals are protected from weather at all times and secured when not in use. <br/>

4. All rental items must be returned to 1st Stop Event Space, LLC within the rental period specified on the “Rental Order” of this agreement. Customer will have extended rental charges of $299 assessed for each 24 hour period it is late. If equipment is not returned within 4 days of the “Drop Off” information date listed below on this Rental Agreement, such failure shall constitute an unauthorized taking and 1st Stop Event Space, LLC may consider such equipment stolen and take all steps necessary to recover said equipment, including charging the customer at cost price thereof, and shall be due upon billing in addition to the rental charge. <br/>

5. In the event a rental item is returned to 1st Stop Event Space, LLC stained, damaged, or in broken condition, customer will be charged five (5) times the rental cost of the piece. Customer agrees to provide a valid credit card number at time of reservation, which will be charged by 1st Stop Event Space, LLC to pay for any such damages. Damage fees will be due upon billing and 1st Stop Event Space, LLC will make a reasonable effort to notify customer of damage fees before the credit card is charged. <br/>

6. DAMAGE WAIVER PLAN. Damage Waiver is available with this rental transaction for an additional fee. If customer accepts Damage Waiver, 1st Stop Event Space, LLC will waive its right to recover from customer all amounts in excess of the amount paid to the customer 2 under customer’s insurance coverage for the retail cost required to repair or replace rented items which are damaged or destroyed while in customer’s possession, provided customer immediately notifies 1st Stop Event Space, LLC of any accident, loss or damage. Damage Waiver is optional. Damage Waiver may be accepted, but it is not a requirement to do so. Damage Waiver is not insurance, nor is it a warranty. Damage Waiver must be accepted prior to taking possession of the rented items, and is not refundable. Damage Waiver is secondary to customer’s own insurance. Some homeowner and business insurance may provide coverage for damage to rented items. Check with agent or broker to determine if such coverage exists. If Damage Waiver is accepted, customer agrees to exercise all rights available under customers’ insurance coverage and assign all claims and proceeds from insurance coverage to 1st Stop Event Space, LLC. Damage Waiver waives customer’s liability for rented items that are returned damaged. If damaged items are not returned, proof of damaged items must be established, and such other evidence as 1st Stop Event Space, LLC may reasonably require. Damage Waiver is not coverage for damage due to neglect or misuse. (Example: Rented Items left out in the rain uncovered and unprotected) Damage Waiver does not waive liability for loss caused by neglect, abuse, vandalism, theft, mysterious or unexplained disappearance, or shortages. customer agrees to furnish, upon request, a written and signed police report filed by customer with respect to such occurrence. <br/>

9. RENTAL DEPOSIT. Rental items will be reserved only upon a receipt of this signed rental agreement and a 50 percent non-refundable deposit. The final balance must be paid 14 days prior to the scheduled reservation date and is non-refundable. <br/>

10. Customer agrees not to use vintage items from any source other than 1st Stop Event Space, LLC including but not limited to china, teacups, mason jars, glassware, floral containers, furniture, props, flatware, and/or linens at the event without express written consent by 1st Stop Event Space, LLC in order to prevent ownership disputes and loss. <br/>

11. Customer acknowledges that the rental property is of a size, design, and capacity selected by customer, and that 1st Stop Event Space, LLC, has not made and does not make any representation, warranty, or covenant, express or implied, with respect to the condition, quality, durability or suitability of the property. 1st Stop Event Space, LLC shall not be liable to customer for any loss, injury, or damage caused directly or indirectly by the rental property, by any inadequacy thereof, or defect therein. <br/>

12. Customer acknowledges that 1st Stop Event Space, LLC’s inventory items are one-of a kind items. 1st Stop Event Space, LLC shall not be liable in the event an inventory is no longer available because of loss or damage caused directly or indirectly to the rental item. <br/>

13. Customer shall not deliver possessions of the rental property to any individual(s) other than 1st Stop Event Space, LLC employees and shall require reasonable identification from such individual(s) prior to surrendering possession. <br/>

14. WEATHER. In the event of forecasted rain for outdoor rentals, customer may cancel order 3 for upholstered furniture, dining chairs, coffee tables, and side tables 24-48 hours in advance of the scheduled rental delivery. The final payment for these rental items will be refunded but not the original 50 percent deposit. Any cancellations due to weather less than 24 hours in advance will incur the full rental and delivery charges. 1st Stop Event Space, LLC and its representatives reserve the exclusive right to not set up furniture outside if it is raining or if rain is imminent. “Forecasted rain” is defined as a 50 percent or greater likelihood of rain predicted for the rental date by Weather.com. <br/>

15. Customer shall indemnify 1st Stop Event Space, LLC against any claim, action, damages, and liability, including attorneys’ fees, arising or connected with customer’s use and possession of the rental property. <br/>

16. WAREHOUSE PICKUPS. Customer agrees to furnish a covered vehicle for any pick ups from the warehouse. For pickups of tables, upholstered furniture, chairs and any large items, customer must provide moving blankets, ratchet straps to securely and safely transport vintage items. Customer understands that these items are fragile and must be treated with extreme care. 1st Stop Event Space, LLC and its associates reserves the right to refuse a customer warehouse pick up if they deem that the means transportable is not suitable. <br/>

Liability Release Indemnification: Customer assumes liability for, and shall indemnify, defend, and hold harmless 1st Stop Event Space, LLC, its agents, employees, officers, and assigns from and against, any and all liabilities, obligations, losses, demands, damages, injuries (including, but not limited to, bodily injury, illness and death), claims, penalties, suits, actions, costs and expenses, including attorneys fee, of whatsoever kind and nature, relating to or arising out of the use, condition (including, but not limited to latent and other defects and whether or not discoverable by lessee or lessor), operation ownership, selection, delivery, leasing, or return of the equipment, regardless of where, how, and by whom operated, or any failure on the part of lessee to perform or comply with the conditions of this lease. Without limiting the generality of the foregoing, lessee shall, at its own cost and expense, defend lessor against all claims, suits or proceedings commenced by anyone in which lessor is named as a party for which lessor is alleged to be liable or responsible as a result of or arising out of the equipment, or any alleged act or omission by lessor, and lessee shall be liable and responsible for all costs, expenses, and attorney’s fees incurred in the defense and/or settlement, judgment, or other resolution thereof. In the event any such is commenced naming lessor as a party. Lessor may, in its sole discretion, elect to defend said action on its own behalf with counsel of its choice, and lessee shall be liable for and reimburse lessee for all costs, expenses, and attorney’s’ fees incurred by lessor in such defense. Purpose of this Clause: The indemnities and assumptions of the liabilities and obligations herein provided for shall continue in full force and effect notwithstanding the expiration or other termination of the lease. In the event lessor fails to perform under the terms of this contract, lessor shall be liable for any attorney’s fees and costs expended by lessee in any claim or action against lessor for breach of contract and/or for specific performance. <br/>

4 Section II. Rental Order 1. Customer agrees that changes to numbers of plates, flatware, glassware, linens, tables, and chairs cannot exceed a 10 percent decrease to the number. Customer understands that 1st Stop Event Space, LLC makes no guarantee that there will be additional inventory available. <br/>

2. Delivery includes assembly and installation rental items in one location at the venue before the event and pick up of the items once it is over. Styling of items is an additional service that must be prearranged with 1st Stop Event Space, LLC. Customer acknowledges that any additional movement of the tables and chairs from the said location will incur additional charges (ie. moving chairs from a ceremony set up to reception) and are not included in the delivery charge. No one but 1st Stop Event Space, LLC is permitted to assemble or break down the tables. I HAVE READ AND AGREE TO THE ABOVE TERMS & CONDITIONS AND ACKNOWLEDGE RECEIPT. THIS CONTRACT IS VALID FOR ALL RENTALS PURCHASED BY THIS CUSTOMER, AND SUPERSEDES ALL PRIOR CONTRACTS.</p>
            </div>
        );
    }
}

export default EventAgreement;